server:
  port: 20020

spring:
  application:
    name: company

  datasource:
    url: jdbc:postgresql://localhost:15432/cupeed-company
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 개발 단계에서는 update, 운영에서는 validate 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    # http://localhost:[port]/swagger로 스웨거 호출 가능.
    path: /swagger

cupeed:
  jwt:
    secret: ${JWT_SECRET_KEY}
    access-expiration-time: 3600000 # 1 hour in milliseconds
    access-header-name: Authorization
    header-prefix: "Bearer "
    swagger-bearer-schema: bearerAuth