spring:
  application:
    name: ai

  datasource:
    url: jdbc:postgresql://localhost:15431/cupeed_ai_db
    username: cupeed_ai_user
    password: cupeed_ai_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

google:
  ai:
    api-key: ${GOOGLE_AI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

server:
  port: 20010

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
