spring:
  application:
    name: slack

  datasource:
    url: jdbc:postgresql://localhost:5433/cupeed_slack_db
    username: cupeed_slack_user
    password: cupeed_slack_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

slack:
  bot-token: ${SLACK_BOT_TOKEN}

server:
  port: 20090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
