spring:
  application:
    name: hub

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15434}/${DB_NAME:cupeed-hub}
    username: ${DB_USERNAME:cupeed-hub-user}
    password: ${DB_PASSWORD:cupeed-hub-pwd}

  jpa:
    hibernate:
      ddl-auto: create  # (none, validate, update, create, create-drop ì¤‘ ì„ íƒ)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true  # ì½˜ì†”ì— SQL ì¶œë ¥ (ê°œë°œìš©)
    open-in-view: false
    # ğŸŒŸ ì¶”ê°€ëœ ì„¤ì •: JPA DDL(í…Œì´ë¸” ìƒì„±)ì´ ì™„ë£Œë  ë•Œê¹Œì§€ ë°ì´í„°ì†ŒìŠ¤ ì´ˆê¸°í™”(data.sql ì‹¤í–‰)ë¥¼ ì§€ì—°ì‹œí‚µë‹ˆë‹¤.
    defer-datasource-initialization: true

  # 2. SQL ì´ˆê¸°í™” ì„¤ì •: data.sql ìë™ ì‹¤í–‰
  sql:
    init:
      mode: always

server:
  port: 20040

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

naver:
  api:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans