services:
  postgres:
    image: postgres:16
    container_name: cupeed_order_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: cupeed_order_user
      POSTGRES_PASSWORD: cupeed_order_pass
      POSTGRES_DB: cupeed_order_db
    ports:
      - "15436:5432"
    volumes:
      - cupeed_order_pg_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # 초기화 스크립트 추가
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cupeed_order_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cupeed_order_pg_data:
