services:
  postgresql:
    container_name: postgresql-product
    image: postgres:18
    restart: always
    environment:
      POSTGRES_DB: cupeed-product
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "15437:5432"
    networks:
      - cupeed-net

#  redis:
#    container_name: redis-cupeed
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    command: ["redis-server"]
#    networks:
#      - cupeed-net

  zipkin:
    container_name: zipkin-cupeed
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"              # Zipkin UI 접근용 포트
    environment:
      - STORAGE_TYPE=mem         # (기본값: 메모리, DB연동도 가능)
    networks:
      - cupeed-net

networks:
  cupeed-net:
    name: cupeed-product
    driver: bridge
