spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # 20010
            - id: ai
              uri: lb://ai
              predicates:
                - Path=/v1/ai-requests/**
            # 20020
            - id: company
              uri: lb://company
              predicates:
                - Path=/v1/companies/**, /internal/v1/companies/**
            # 20030
            - id: delivery
              uri: lb://delivery
              predicates:
                - Path=/v1/deliveries/**
            # 20040
            - id: hub
              uri: lb://hub
              predicates:
                - Path=/v1/hubs/**
              filters:
                - StripPrefix=0
            # 20050
            - id: hubroute
              uri: lb://hubroute
              predicates:
                - Path=/v1/hub-routes/**
              filters:
                - StripPrefix=0
            # 20060
            - id: order
              uri: lb://order
              predicates:
                - Path=/v1/orders/**
            # 20070
            - id: product
              uri: lb://product
              predicates:
                - Path=/v1/products/**, /internal/v1/products/**
            # 20080
            - id: user
              uri: lb://user
              predicates:
                - Path=/v1/users/**, /v1/auth/**
          discovery:
            locator:
              enabled: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

cupeed:
  jwt:
    secret: ${JWT_SECRET_KEY}
    access-expiration-time: 3600000 # 1 hour in milliseconds
    access-header-name: Authorization
    header-prefix: "Bearer "
    swagger-bearer-schema: bearerAuth